### ISSUE TITLE
Use of wildcards

### ISSUE THREAD

**Issue by Slugger70** [gvlproject/python-genomespaceclient#1]
Allow the use of wildcards inside file URL's. For example, when cp-ing data from genomespace:

```
genomespace -u <user> -p <password> cp https://something.somewhere.com/filepath/*.h5.gz .
```

will copy all of the h5.gz files inside the filepath directory to the local filesystem..

**Comment by madiflannery** [comment]
Do you want this to happen for both uploads and downloads @Slugger70 ?

**Comment by Slugger70** [comment]
yes please!

**Comment by madiflannery** [comment]
Unassigning myself from this cause I won't get time before I leave... :(

**Comment by nuwang** [comment]
Fixed in commit: https://github.com/gvlproject/python-genomespaceclient/commit/62350e26fe0c383a42ad6c646b920a38f744d9fe
