### ISSUE TITLE
Doesn't upload files larger than 5 Gig

### ISSUE THREAD

**Issue by MartinPaulo** [gvlproject/python-genomespaceclient#5]
If I try to upload a file larger than 5 Gig in size it eventually fails.

I believe that the defect really lies in the underlying `cloudbridge` library.
My logic is as follows: 
`SwiftStorageHandler` delegates to the `cloudbridge` `OpenStackBucketObject` `upload_from_file` method. This in turn eventually lands up calling the OpenStack `swiftclient.client.py` `Connection` `put_object` method: which is a low level method that does not attempt to chunk files > 5Gig in size. Hence when you hit the 5 Gig wall, Swift complains.

The OpenStack utility class `SwiftService` has an upload method that will chunk files if you set the `segment_size` option. Thus this method will handle files > 5 Gig with aplomb.  I've tested this with some rough and ready sample code that chunks any file larger than 1 Gig (arbitrarily chosen):

```python
from swiftclient.service import SwiftService, SwiftUploadObject
config = {'os_username': 'a_username',
          'os_password': 'a_password',
          'os_auth_url': 'https://keystone.somewhere.org:5000/v2.0/',
          'os_project_name': 'A_Project,
          'os_region_name': 'A_region'
          }
path = '/Users/SomeUser/Desktop/Demo/6Gig.txt'
file_size = os.path.getsize(path)
segment_size = 1048576000 # 1 Gig
options = {} if file_size < segment_size else {'segment_size': segment_size}
with SwiftService(options=config) as sw:
    suo = SwiftUploadObject(path, object_name='6Gig.txt')
    results = sw.upload('test', [suo,], options=options)
    for r in results:
        print('%s' %r)
```
So IMHO this should be fixed in the `cloudbridge` library: but going out to the service utilities ruins the elegance of the library :(

**Comment by nuwang** [comment]
Aah yes :-) One of the reasons the logic was moved to cloudbridge was because transparently handling files >5GB was needed in cloudbridge too, so I figured there was no point in implementing it in two places - plus the genomespaceclient code becomes simpler.

I think this code will fit perfectly into cloudbridge - would you mind creating the issue there and if possible, issuing a pull request against cloudbridge? The only thing is that a swift connection object is already available in cloudbridge (https://github.com/gvlproject/cloudbridge/blob/master/cloudbridge/cloud/providers/openstack/provider.py#L239), is it possible for the SwiftService to use that connection straight away?

**Comment by nuwang** [comment]
@MartinPaulo Or more precisely, the connection is available as self._provider.swift within the upload_file method.

**Comment by MartinPaulo** [comment]
I'll give it a go. The first problem I'm seeing is that the SwiftService has a connection factory that it uses internally - as it can have more than one Connection instance in use, if I'm reading the code correctly.

**Comment by nuwang** [comment]
Thanks, much appreciated. I guess we could refactor the openstack provider code internally to return the connection config instead, but that would probably end up duplicating some code/logic and be slower. (unless we directly pass in the session_token or something)

For CloudBridge, can you do a pull from fork? That is, fork off the cloudbridge repo, commit changes in fork, and then pull from fork to upstream? (That's the model we've been following)

**Comment by MartinPaulo** [comment]
I'll give it a go. The first problem I'm seeing is that the SwiftService has a connection factory that it uses internally - as it can have more than one Connection instance in use, if I'm reading the code correctly.

I've opened https://github.com/gvlproject/cloudbridge/issues/35 on cloudbridge
